### ISSUE TITLE
Settings showing white screen. Might be a dark/light mode issue

### ISSUE THREAD

**Issue by jonnneehh** [yazninja/cssweng#13]
![image](https://user-images.githubusercontent.com/78949765/203552593-99a7e5be-9bb1-4a2e-b23b-c3ead0526068.png)

**Comment by yazninja** [comment]
will try to fix this next update, may i know what OS u use, and version number if u know

**Comment by jonnneehh** [comment]
> will try to fix this next update, may i know what OS u use, and version number if u know

Edition	Windows 10 Pro
Version	22H2
Installed on	‎11/‎1/‎2021
OS build	19045.2251
Experience	Windows Feature Experience Pack 120.2212.4180.0
